### ISSUE TITLE
Can not move the window?

### ISSUE THREAD

**Issue by phoenixic** [marcio199226/ytd#2]
After running the app (v  v0.4.1-alpha ) on macbook m1 , I tried to move the window by trying to grab the top bar with the mouse, but it does nothing and I can not move the window .

**Comment by marcio199226** [comment]
Yes the window cannot drag, I will give it a look but it depends if dragging is supported by wails v2-alpha, I didn't notice that behaviour since I used it in fullscreen mode always

**Comment by marcio199226** [comment]
Due to: https://github.com/wailsapp/wails/issues/1346 so until the wails core of ytd will not be updated I think there is no chances to enable "dragging window"

**Comment by marcio199226** [comment]
Hi @Kazako now you can drag the window in the latest release v0.5.0-beta.
